print(" ")
print("What's your name?")
input("Name: ")
print(" ")
print("Start your story!")
print("It's 7am and your alarm goes off. What do you do?")
print("You have work later!")
print("Get up - 1")
print("Stay in bed - 2")
print(" ")
beginning = int(input("What do you want to do? "))
if (beginning != 1) and (beginning != 2):
    print(" ")
    print("-PLAYER DOESN'T WANT TO FOLLOW DIRECTIONS ENDING-")
if beginning == 1:
    print(" ")
    print("You get out of bed.")
    print("You go to the bathroom and you take a piss.")
    print("The toothbrush looks chewed up.")
    print("Garfield your dog might've chewed it up while you were sleeping.")
    print("Will you brush your teeth?")
    print("Yes - 1")
    print("No - 2")
    print(" ")
    Brushteeth = int(input("Do you want to brush your teeth? "))
    if (Brushteeth != 1) and (Brushteeth != 2):
        print(" ")
        print("-PLAYER DOESN'T WANT TO FOLLOW DIRECTIONS ENDING-")
    if Brushteeth == 1:
        print(" ")
        print("You brush your teeth.")
        print("You brush your teeth for a long time.")
        print("Maybe too long.")
        print("You go in your car and takes you 30 minutes to drive to work.")
        print("You're late for work.")
        print("Your boss yells at you for being ten minutes late.")
        print("Do you tell the truth?")
        print("I was brushing my teeth.(TRUTH) - 1")
        print("My dog was sick and I needed to take a stop at the vet.(LIE) - 2")
        print(" ")
        boss = int(input("Do you tell the truth or will you lie? "))
        if (boss != 1) and (boss != 2):
            print(" ")
            print("-PLAYER DOESN'T WANT TO FOLLOW DIRECTIONS ENDING-")
        if boss == 1:
            print(" ")
            print("'YOU IRRESPONSIBLE LOSER'")
            print("You got in trouble with your boss.")
            print("Your boss gives you a harsh scolding for a while")
            print("After he was done you realize that it's already time to leave.")
            print("Aw man.")
            print(" ")
            print("-SCOLDING ENDING-")
        if boss == 2:
            print(" ")
            print("'GOOD JOB, TAKING CARE OF YOUR DOG LIKE A RESPONSIBLE PERSON'")
            print("Your boss is proud of you.")
            print("Oh dear")
            print("The person you admire walks by you.")
            print("Your heart races.")
            print("Your crush realizes you're staring.")
            print("Talk to your crush?")
            print("Yes - 1")
            print("No - 2")
            print(" ")
            crushbrush = int(input("Will you talk to your crush? "))
            if (boss != 1) and (boss != 2):
                print(" ")
                print("-PLAYER DOESN'T WANT TO FOLLOW DIRECTIONS ENDING-")
            if crushbrush == 1:
                print(" ")
                print("'H-h-h-h-h'")
                print("Your friend rushes in and interrupts your sentence.")
                print("That's what you get for brushing your teeth for ten minutes.")
                print("'HEY MAN I GOT A PARTY TONIGHT WANNA COME??'")
                print("Your crush walks away feeling awkward.")
                print("'IT'S GONNA BE REALLY FUN CMON!")
                print("Go to the party?")
                print("Yes - 1")
                print("No - 2")
                print(" ")
                partybrush = int(input("Will you skip work and go to the party? "))
                if (partybrush != 1) and (partybrush != 2):
                    print(" ")
                    print("-PLAYER DOESN'T WANT TO FOLLOW DIRECTIONS ENDING-")
                if partybrush == 1:
                    print(" ")
                    print("You party animal.")
                    print("You drank a bottle of beer")
                    print("But you have low alcohol tolerence.")
                    print("'HEY MAN HAVE A COUPLE MORE BEERS WITH US'")
                    print("Drink another one?")
                    print("Yes - 1")
                    print("No - 2")
                    print(" ")
                    drinkbrush = int(input("Will you drink another? "))
                    if (drinkbrush != 1) and (drinkbrush != 2):
                        print(" ")
                        print("-PLAYER DOESN'T WANT TO FOLLOW DIRECTIONS ENDING-")
                    if drinkbrush == 1:
                        print(" ")
                        print("You drink another.")
                        print("Your head starts to get dizzy and you fall over.")
                        print("Your friends praise you for being a party animal.")
                        print("You love the attention.")
                        print("You and your friends drink the night away.")
                        print("You wake up with 10 missed calls from your boss the next morning.")
                        print("Oh no.")
                        print(" ")
                        print("-PARTY ANIMAL ENDING-")
                    if drinkbrush == 2:
                        print(" ")
                        print("You politely decline and walk out of the bar")
                        print("You walk in the alleyway and see a fight going on.")
                        print("There's a crowd around them cheering.")
                        print("Someone's getting beat up!")
                        print("Help the poor child?")
                        print("Yes - 1")
                        print("No - 2")
                        print(" ")
                        fightbrush = int(input("Will you help the guy? "))
                        if (fightbrush != 1) and (fightbrush != 2):
                            print(" ")
                            print("-PLAYER DOESN'T WANT TO FOLLOW DIRECTIONS ENDING-")
                        if fightbrush == 1:
                            print(" ")
                            print("You run in and break up the fight.")
                            print("The crowd boos you and walks away.")
                            print("What a party pooper.")
                            print("The beat up guy thanks you and offers you a couple of bucks.")
                            print("You guys become friends.")
                            print(" ")
                            print("-NEW FRIEND ENDING-")
                        if fightbrush == 2:
                            print(" ")
                            print("You don't want to interfere with that.")
                            print("You sneak into your car and drive home sober.")
                            print("You brush your teeth once more and go to bed.")
                            print("You turn on your TV to watch the late night shows.")
                            print("'BREAKING NEWS!'")
                            print("Turns out there was a murder in the bar you were just in.")
                            print("The victim on the screen showed the guy that was getting beat.")
                            print("Oh no.")
                            print("You turn off the TV and put the blankets over your face.")
                            print("You try to sleep but you end up staying up all night.")
                            print(" ")
                            print("-GUILTY ENDING-")
                if partybrush == 2:
                    print(" ")
                    print("You don't want to skip work just for a party.")
                    print("Your responsibilities are your priorities.")
                    print("Money is more important!")
                    print("You spend the rest of the day making graphs.")
                    print("You make some extra money for the day.")
                    print("Maybe you can buy yourself some icecream to eat away your sorrow.")
                    print("Next time you'll talk to your crush, right?")
                    print(" ")
                    print("-REGULAR ENDING-")
            if crushbrush == 2:
                print(" ")
                print(" ")
                print("You walk away.")
                print("You go to your desk and work the night away.")
                print("You see your friend walk over to your crush")
                print("They're talking to each other having fun.")
                print("You slouch in your seat and isolate yourself so no one can see you.")
                print("You feel like poop for the rest of the day.")
                print(" ")
                print("-SAD ENDING-")
    if Brushteeth == 2:
        print(" ")
        print("You don't brush your teeth.")
        print("Disgusting.")
        print("You go to work with your nasty teeth.")
        print("You go in your car and takes you 30 minutes to drive to work.")
        print("Your boss sees you and praises you for being on time")
        print("You feel good about yourself.")
        print("Oh dear")
        print("The person you admire walks by you.")
        print("Your heart races.")
        print("Your crush realizes you're staring.")
        print("You have nasty teeth though.")
        print("Risk it?")
        print("Talk to your crush?")
        print("Yes - 1")
        print("No - 2")
        print(" ")
        crushnobrush = int(input("Will you talk to your crush? "))
        if (crushnobrush != 1) and (crushnobrush != 2):
            print(" ")
            print("-PLAYER DOESN'T WANT TO FOLLOW DIRECTIONS ENDING-")
        if crushnobrush == 1:
            print(" ")
            print("Gross")
            print("'H-h-h-h-hi...''")
            print("You manage to get the words out of your mouth.")
            print("The burrito you ate the night before made you burp a little.")
            print("Your crush laughs and you guys have a friendly conversation.")
            print("Good thing it's allergy season and she can't smell.")
            print("Your friend rushes in and interrupts your conversation.")
            print("'HEY MAN I GOT A PARTY TONIGHT WANNA COME??'")
            print("Your crush says bye and walks away.")
            print("'IT'S GONNA BE REALLY FUN CMON!")
            print("Go to the party?")
            print("Yes - 1")
            print("No - 2")
            print(" ")
            partynobrush = int(input("Will you skip work to go to the party? "))
            if (partynobrush != 1) and (partynobrush != 2):
                print(" ")
                print("-PLAYER DOESN'T WANT TO FOLLOW DIRECTIONS ENDING-")
            if partynobrush == 1:
                print(" ")
                print("You party animal.")
                print("You drank a bottle of beer")
                print("But you have low alcohol tolerence.")
                print("'HEY MAN HAVE A COUPLE MORE BEERS WITH US'")
                print("Drink another one?")
                print("Yes - 1")
                print("No - 2")
                print(" ")
                drinknobrush = int(input("Will you drink another? "))
                if (drinknobrush != 1) and (drinknobrush != 2):
                    print(" ")
                    print("-PLAYER DOESN'T WANT TO FOLLOW DIRECTIONS ENDING-")
                if drinknobrush == 1:
                    print(" ")
                    print("You drink another.")
                    print("Your head starts to get dizzy and you fall over.")
                    print("Your friends praise you for being a party animal.")
                    print("You love the attention.")
                    print("You and your friends drink the night away.")
                    print("You wake up with 10 missed calls from your boss the next morning.")
                    print("Oh no.")
                    print(" ")
                    print("-PARTY ANIMAL ENDING-")
                if drinknobrush == 2:
                    print(" ")
                    print("You politely decline and walk out of the bar.")
                    print("You walk through the alleyway and get in your car.")
                    print("You barely see two people yelling at each other but decide to ignore it.")
                    print("You get in your car and drive home sober.")
                    print("You finally brush your teeth and go to bed.")
                    print("You turn on your TV to watch the late night shows.")
                    print("'BREAKING NEWS!'")
                    print("Turns out there was a murder in the bar you were just in.")
                    print("Good thing you didn't stay.")
                    print("You feel lucky and good about yourself.")
                    print(" ")
                    print("-GOOD ENDING-")
            if partynobrush == 2:
                print(" ")
                print("You don't want to skip work just for a party.")
                print("Your responsibilities are your priorities.")
                print("Money is more important!")
                print("You spend the rest of the day making graphs.")
                print("You make some extra money for the day.")
                print("Maybe you can take your crush on a date with this extra cash!")
                print(" ")
                print("-HOPEFUL ENDING-")
        if crushnobrush == 2:
            print(" ")
            print("You walk away.")
            print("You go to your desk and work the night away.")
            print("You see your friend walk over to your crush")
            print("They're talking to each other having fun.")
            print("You slouch in your seat and isolate yourself so no one can see you.")
            print("You feel like poop for the rest of the day.")
            print(" ")
            print("-SAD ENDING-")
if beginning == 2:
    print(" ")
    print("You stay in bed.")
    print("You don't wake up until 10am.")
    print("Should you just not go to work?")
    print("Yes - 1")
    print("No - 2")
    print(" ")
    lazy = int(input("Go to work? "))
    if (lazy != 1) and (lazy != 2):
        print(" ")
        print("-PLAYER DOESN'T WANT TO FOLLOW DIRECTIONS ENDING-")
    if lazy == 1:
        print(" ")
        print("'YOU IRRESPONSIBLE LOSER'")
        print("You got in trouble with your boss.")
        print("'GO TO THE CORNER AND THINK ABOUT WHAT YOU'VE DONE'")
        print("You sit in the corner and is shamed by your coworkers.")
        print("Your crush walks by you avoiding eye contact.")
        print("Good job.")
        print(" ")
        print("-BAD ENDING-")
    if lazy == 2:
        print(" ")
        print("You stay in bed for the whole day.")
        print("You play video games and watch TV.")
        print("You eat a bunch of chips and candy.")
        print("You gain 5 pounds.")
        print("You feel disgusting.")
        print("Ten missed calls from your boss.")
        print("Oh no.")
        print(" ")
        print("-LAZY ENDING-")
